.PHONY:quectel_ocpu_app
quectel_ocpu_app:
	(cd project/$(TARGET)/$(PROJECT)/quec_open && $(MAKE) V=$(V) -f Makefile all)

.PHONY:clean
clean:
	(cd project/$(TARGET)/$(PROJECT)/quec_open && $(MAKE) -f Makefile clean)

.PHONY:clean_ocpu_app
clean_ocpu_app:
	(cd project/$(TARGET)/$(PROJECT)/quec_open && $(MAKE) -f Makefile clean)
